# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

screen_analysis_task:
  description: >
    Analyze the screens you got and find the most relevant information.
    Make sure you find any interesting and relevant information given
    button positions, links, and other actionable elements.
  expected_output: >
    A list with l0 Ui elements, with positions, links, and other actionable elements.
  agent: screen_analyst

action_planning_task:
  description: >
    Review the context you got and develop an actionable plan based on the data and insights.
    Make sure to include screenshots and visual aids to help understand the steps needed.
  expected_output: >
    A detailed action plan with steps, including screenshots and visual aids.
    Formatted as markdown without '```'
  agent: action_planner_with_screenshots

computer_action_generation_task:
  description: >
    Generate actionable steps based on the data and insights you got.
    Make sure to include any relevant information and actionable steps.
  expected_output: >
    A list of actionable steps, with detailed descriptions and any relevant information.
    actions should be formatted as markdown without '```'
    and click positions with json format.
  agent: computer_action_generator